/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TonersRouteImport } from './routes/toners'
import { Route as SuppliesRouteImport } from './routes/supplies'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrintersRouteImport } from './routes/printers'
import { Route as PaperRouteImport } from './routes/paper'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'

const TonersRoute = TonersRouteImport.update({
  id: '/toners',
  path: '/toners',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliesRoute = SuppliesRouteImport.update({
  id: '/supplies',
  path: '/supplies',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintersRoute = PrintersRouteImport.update({
  id: '/printers',
  path: '/printers',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperRoute = PaperRouteImport.update({
  id: '/paper',
  path: '/paper',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/paper': typeof PaperRoute
  '/printers': typeof PrintersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supplies': typeof SuppliesRoute
  '/toners': typeof TonersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/paper': typeof PaperRoute
  '/printers': typeof PrintersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supplies': typeof SuppliesRoute
  '/toners': typeof TonersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/paper': typeof PaperRoute
  '/printers': typeof PrintersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supplies': typeof SuppliesRoute
  '/toners': typeof TonersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/paper'
    | '/printers'
    | '/sitemap.xml'
    | '/supplies'
    | '/toners'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/paper'
    | '/printers'
    | '/sitemap.xml'
    | '/supplies'
    | '/toners'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/paper'
    | '/printers'
    | '/sitemap.xml'
    | '/supplies'
    | '/toners'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  PaperRoute: typeof PaperRoute
  PrintersRoute: typeof PrintersRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuppliesRoute: typeof SuppliesRoute
  TonersRoute: typeof TonersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toners': {
      id: '/toners'
      path: '/toners'
      fullPath: '/toners'
      preLoaderRoute: typeof TonersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplies': {
      id: '/supplies'
      path: '/supplies'
      fullPath: '/supplies'
      preLoaderRoute: typeof SuppliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printers': {
      id: '/printers'
      path: '/printers'
      fullPath: '/printers'
      preLoaderRoute: typeof PrintersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper': {
      id: '/paper'
      path: '/paper'
      fullPath: '/paper'
      preLoaderRoute: typeof PaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  PaperRoute: PaperRoute,
  PrintersRoute: PrintersRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuppliesRoute: SuppliesRoute,
  TonersRoute: TonersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
